version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"

  db:
    image: mysql:latest
    environment:
      POSTGRES_DB: sql12647073
      POSTGRES_USER: sql12647073
      POSTGRES_PASSWORD: hkYAruWkmD